### ISSUE TITLE
ESP8266 support

### ISSUE THREAD

**Issue by Juice10** [hubsif/arduino-dali#1]
Thanks for the awesome library! I'm trying to use this together with an ESP8266 and an MikroE Click DALI 2 module. Unfortunately the ESP8266 doesn't run on avr architecture so some of the external libraries currently don't support the ESP8266. It would be great if this library could add support for it since its such a popular platform.

Keep up the great work!

**Comment by hubsif** [comment]
Thank you, @Juice10!
Through those external libraries this DALI library makes use of AVR hardware features, i.e. external interrupts and timers. These are different on each microchip platform and thus cannot have common code, at least not without some abstraction layer.
I currently do not intend to extend the DALI library to support ESP8266, but I certainly would accept a pull request that adds this platform 😉.
